cluster.name: opensearch-cluster
node.name: opensearch-node1

# Paths
path.data: /usr/share/opensearch/data
path.logs: /usr/share/opensearch/logs

# Network
network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300

# Discovery
discovery.type: single-node
cluster.initial_master_nodes: ["opensearch-node1"]

# Bootstrap
bootstrap.memory_lock: true

# Security Plugin Configuration
plugins.security.disabled: false
plugins.security.ssl.transport.pemcert_filepath: certificates/opensearch.pem
plugins.security.ssl.transport.pemkey_filepath: certificates/opensearch-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: certificates/root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false

plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: certificates/opensearch.pem
plugins.security.ssl.http.pemkey_filepath: certificates/opensearch-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: certificates/root-ca.pem

plugins.security.allow_unsafe_democertificates: false
plugins.security.allow_default_init_securityindex: true
plugins.security.authcz.admin_dn:
  - CN=admin,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA

plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]

# Performance
indices.query.bool.max_clause_count: 1024
search.max_buckets: 250000

# Compatibility
compatibility.override_main_response_version: true

# Logging
logger.level: INFO

# Cross-cluster replication
plugins.replication.autofollow.fetch_poll_interval: 30s

# Index State Management
plugins.index_state_management.enabled: true
plugins.index_state_management.job_interval: 5

# Alerting
plugins.alerting.enabled: true

# SQL
plugins.sql.enabled: true

# Cross Cluster Search
plugins.cross_cluster_replication.enabled: true

# Security Analytics
plugins.security_analytics.enabled: true

# Machine Learning
plugins.ml_commons.enabled: true
plugins.ml_commons.only_run_on_ml_node: false
plugins.ml_commons.native_memory_threshold: 90
plugins.ml_commons.max_model_on_node: 10

# Index settings
action.auto_create_index: +*

# Thread pool settings
thread_pool:
  analyze:
    size: 1
  get:
    size: 8
  index:
    size: 8
  search:
    size: 8
  write:
    size: 8

# Circuit breaker settings
indices.breaker.total.use_real_memory: false
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 60%
indices.breaker.request.limit: 60%

# Graylog compatibility
action.destructive_requires_name: false