<?php
/**
 * MISP Configuration File
 */

$config = array(
    'debug' => 0,
    'MISP' => array(
        'baseurl' => 'https://localhost',
        'external_baseurl' => '',
        'host_org_id' => 1,
        'email' => 'admin@example.com',
        'contact' => 'admin@example.com',
        'cveurl' => 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=',
        'disablerestalert' => false,
        'showorg' => true,
        'showorgalternate' => false,
        'background_jobs' => true,
        'cached_attachments' => false,
        'email_otp_enabled' => false,
        'email_otp_length' => 6,
        'email_otp_validity' => 300,
        'take_ownership_xml_import' => false,
        'terms_download' => false,
        'showCorrelationsOnIndex' => true,
        'showProposalsOnIndex' => true,
        'showStatisticsOnIndex' => true,
        'showTrendsOnIndex' => true,
        'showSightingsCountOnIndex' => false,
        'showDiscussionsOnIndex' => false,
        'showTaxonomySelectOnEventCreation' => false,
        'showTaxonomySelectOnEventUpdate' => false,
        'showTaxonomySelectOnEventView' => false,
        'live' => true,
        'language' => 'eng',
        'default_event_distribution' => '1',
        'default_attribute_distribution' => 'event',
        'default_event_threat_level' => '4',
        'default_event_tag_collection' => 0,
        'tagging' => true,
        'full_tags_on_event_index' => true,
        'footer_logo' => '',
        'home_logo' => '',
        'main_logo' => '',
        'org' => 'ORGNAME',
        'uuid' => '',
        'logo' => '',
        'footermidleft' => 'This is an initial install',
        'footermidright' => 'Please configure and harden accordingly',
        'footerpart1' => 'Powered by MISP',
        'footerpart2' => '© MISP Project',
        'footer_logo' => '',
        'sync_cas_timestamp' => false,
        'proposals_block_attributes' => false,
        'completely_disable_correlation' => false,
        'allow_disabling_correlation' => false,
        'disable_cached_exports' => false,
        'username_in_response_header' => false,
        'hide_organisation_index_from_users' => false,
        'disable_emailing' => false,
        'disable_user_self_management' => false,
        'disable_user_add' => false,
        'block_event_alert' => false,
        'block_event_alert_tag' => false,
        'block_old_event_alert' => false,
        'block_old_event_alert_age' => '',
        'incoming_tags_disabled_by_default' => false,
        'maintenance_message' => 'Great things are happening! MISP is undergoing maintenance, but will return shortly. You can contact the administration at $email.',
        'footerpart1' => 'Powered by MISP',
        'footerpart2' => '© MISP Project',
        'showorgalternate' => false,
        'event_view_filter_fields' => 'id, uuid, value, comment, type, category, Tag.name',
        'manage_workers' => true,
        'delegation' => false,
        'showCorrelationsOnIndex' => true,
        'showProposalsOnIndex' => true,
        'showStatisticsOnIndex' => true,
        'showTrendsOnIndex' => true,
        'showSightingsCountOnIndex' => false,
        'showDiscussionsOnIndex' => false,
        'correlation_default_threshold' => 5,
        'full_tags_on_event_index' => 2,
        'welcome_text_top' => '',
        'welcome_text_bottom' => '',
        'attachments_dir' => APP . 'files' . DS,
        'download_attachments_on_load' => true,
        'event_alert_republish_ban' => false,
        'event_alert_republish_ban_threshold' => 5,
        'event_alert_republish_ban_refresh_on_retry' => false,
        'tmpdir' => '/tmp',
        'custom_css' => '',
        'custom_jquery' => '',
        'disable_auto_logout' => false,
        'ssdeep_correlation_threshold' => 40,
        'max_correlations_per_event' => 5,
        'bg_processing' => false,
        'store_api_access_time' => false,
        'disable_cached_exports' => false,
        'export_services_url' => '',
        'export_services_token' => '',
        'export_services_enable' => false
    ),
    'GnuPG' => array(
        'onlyencrypted' => false,
        'email' => 'admin@admin.test',
        'homedir' => '',
        'password' => '',
        'bodyonlyencrypted' => false,
        'sign' => true,
        'binary' => '/usr/bin/gpg'
    ),
    'SMIME' => array(
        'enabled' => false,
        'email' => 'admin@admin.test',
        'cert_public_sign' => '/var/www/MISP/.smime/email@address.com.pem',
        'key_sign' => '/var/www/MISP/.smime/email@address.com.key',
        'password' => ''
    ),
    'Proxy' => array(
        'host' => '',
        'port' => '',
        'method' => '',
        'user' => '',
        'password' => ''
    ),
    'SecureAuth' => array(
        'amount' => 5,
        'expire' => 300
    ),
    'Security' => array(
        'salt' => '',
        'auth_key' => '',
        'advanced_authkeys' => false,
        'password_policy_length' => 12,
        'password_policy_complexity' => '/^((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/',
        'self_registration_message' => 'If you would like to send us a registration request, please fill out the form below. Make sure you fill out as much information as possible in order to ease the task of the administrators.',
        'password_policy_complexity' => '/^((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/'
    ),
    'Session' => array(
        'autoRegenerate' => false,
        'timeout' => 60,
        'cookieTimeout' => 3600,
        'defaults' => array(
            'timeout' => 60,
            'cookieTimeout' => 3600
        )
    ),
    'site_admin_debug' => false,
    'Plugin' => array(
        'ZeroMQ_enable' => false,
        'ZeroMQ_host' => '127.0.0.1',
        'ZeroMQ_port' => 50000,
        'ZeroMQ_redis_host' => 'localhost',
        'ZeroMQ_redis_port' => 6379,
        'ZeroMQ_redis_database' => 1,
        'ZeroMQ_redis_namespace' => 'mispq',
        'ZeroMQ_include_attachments' => false,
        'ZeroMQ_tag_notifications_enable' => false,
        'ZeroMQ_audit_notifications_enable' => false,
        'ElasticSearch_logging_enable' => false,
        'ElasticSearch_connection_string' => 'http://localhost:9200',
        'ElasticSearch_log_index' => 'misp',
        'S3_enable' => false,
        'S3_bucket_name' => '',
        'S3_region' => '',
        'S3_aws_access_key' => '',
        'S3_aws_secret_key' => '',
        'Kafka_enable' => false,
        'Kafka_brokers' => 'kafka:9092',
        'Kafka_rdkafka_config' => '/etc/rdkafka.ini',
        'Kafka_include_attachments' => false,
        'Kafka_confluent_schema_registry_url' => '',
        'Kafka_schema_registry_username' => '',
        'Kafka_schema_registry_password' => ''
    ),
    'SimpleBackgroundJobs' => array(
        'enabled' => true,
        'redis_host' => 'redis',
        'redis_port' => 6379,
        'redis_password' => '',
        'redis_database' => 1,
        'redis_namespace' => 'SimpleBackgroundJobs',
        'max_job_history_ttl' => 86400
    )
);
?>